### ISSUE TITLE
Just run it according to the Readme will produce NaN

### ISSUE THREAD

**Issue by Yikai-Wu** [gkdziugaite/pacbayes-opt#3]
I just run it using exact the same commands as in the Readme but the result is NaN.

**Comment by wgharbieh** [comment]
Which value is NaN? Did you run the code in an environment that contains the same package versions as the ones specified in the Readme Requirements?

**Comment by UCL-Abbas** [comment]
Hello @wgharbieh @gkdziugaite, I am observing the same issue. The stochasitc training via SGD runs fine, but when I run the PAC-Bayes part I get:

2020-11-13 23:36:56.589612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 14984 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-16GB, pci bus id: 0000:d8:00.0, compute capability: 7.0)
Before discretization
[nan] [nan]
Traceback (most recent call last):
  File "snn/experiments/run_pacb.py", line 38, in <module>
    complete_args["drop_lr"], complete_args["lr_factor"], complete_args["seed"], complete_args["trainw"])
  File "snn/experiments/run_pacb.py", line 22, in run_pacb
    model.evaluate_SNN_accuracy(testX, testY, weights_rand_init, N_SNN_samples=1, save_dict=save_dict)
  File "/shared/Abbas/pade/pacbayes-opt/snn/core/network.py", line 403, in evaluate_SNN_accuracy
    jdisc_up   = np.float32(math.ceil(jdisc))


The above appears after some iterations which run fine. I made the APIs and libs match the exact versions cited in the README.

@wgharbieh can I suggest perhaps providing the output of "pip freeze" which lists all python APIs and versions installed -

**Comment by wgharbieh** [comment]
Just merged https://github.com/gkdziugaite/pacbayes-opt/pull/4, this should fix the issue. @UCL-Abbas the pip freeze suggestion is a good one, will add it to the readme.

**Comment by wgharbieh** [comment]
Closing this issue since there are no further follow ups.
